Add `ErrorHandlerWithOpts`
oapi-codegen/nethttp-middleware pull request #15
Opened 2024-04-25 12:39 UTC by mikeschinkel

This PR adds an alternate custom error handlers with an additional `opts` parameter that allows a custom error handler access to the incoming `*http.Request`, then matched `routes.Route`, and [the relevant `context.Context`](https://github.com/oapi-codegen/nethttp-middleware/pull/14).

My use-case for why the Route is needed is to be able to determine the approach Content-Type for an error response; should it be `application/json`, `text/html` or something else?

I added `Request` as I originally thought I would need it, but I didn't. Still, I can easily see that others might so it doesn't seem a harm to provide it.

I added `Context` to explicitly fulfill the use-case for #13 & #14, and hopefully to supercede them.

Lastly, I chose an `opts` parameter passing in `ErrorHandlerOpts` so that future needs could be accommodated easily by just adding a property without needing to add yet another signature and yet another type of error func.

P.S. I also had to modify private function `validateRequest()` get it to return the matched `routers.Route` — as well as that that called it — given that access to the `Route` was the motivation for this PR.

2024-12-31 22:27 UTC, MattiasMartens requested changes

2024-12-31 22:27 UTC, MattiasMartens commented on oapi_validate.go
> +	context.Context
Adding a field here `error` to capture the original error would be helpful (cf: https://github.com/oapi-codegen/nethttp-middleware/issues/11#issuecomment-2548229196)

2024-12-31 22:27 UTC, MattiasMartens commented on oapi_validate.go
> +						options.ErrorHandlerWithOpts(w, err.Error(), statusCode, ErrorHandlerOpts{
If change to `ErrorHandlerOpts` is implemented then we could add here:
```suggestion
						options.ErrorHandlerWithOpts(w, err.Error(), statusCode, ErrorHandlerOpts{
						Error: err,
```

2025-01-06 06:59 UTC, mikeschinkel commented on oapi_validate.go
> +	context.Context
@MattiasMartens — Thank you for that suggested change.  Assuming I understood your suggestion then I think it is an excellent idea. Actually, disappointed in myself for not thinking of it initially.

I made that change to the PR. Please review the PR to make sure I correctly understood what you were suggesting.

2025-01-06 06:59 UTC, mikeschinkel commented on oapi_validate.go
> +						options.ErrorHandlerWithOpts(w, err.Error(), statusCode, ErrorHandlerOpts{
I made that change to the PR. Please review the PR to make sure I correctly understood what you were suggesting.

2025-01-20 15:47 UTC, MattiasMartens approved these changes
LGTM

2025-01-31 12:07 UTC, gk-peytz commented
Thanks guys. Also looking for such functionality.

2025-04-24 07:57 UTC, jamietanna commented
Thanks all for the patience and suggestions - I'm looking at getting this tackled via https://github.com/oapi-codegen/nethttp-middleware/pull/35 - please take a look at the signature and let me know thoughts

(This will be merged in the next couple of days, and anyone who's contributed suggestions will get a `Co-Authored-By` in this change, so even though it won't show as a "merged PR" from you, it'll definitely show as you having contributed to the work!)

2025-04-24 15:05 UTC, jamietanna commented
Replaced by https://github.com/oapi-codegen/nethttp-middleware/pull/35

2025-04-24 15:05 UTC, closed without merging